import { BookingContextProvider } from "../../context/booking.context";
import "../styles/globals.css";
import "../styles/normalize.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getCurrentDate() {
  const now = new Date();
  const day = now.getDate().toString().padStart(2, '0'); // добавляем ведущий ноль, если число меньше 10
  const month = (now.getMonth() + 1).toString().padStart(2, '0'); // добавляем ведущий ноль, если месяц меньше 10
  const year = now.getFullYear();
  return `${year}-${month}-${day}`;
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <BookingContextProvider campus={"Корпус"} date={getCurrentDate()} guests={2}>
        <body className={inter.className}>{children}</body>
      </BookingContextProvider>
    </html>
  );
}
